language: none

build:
    pre_ci:
        - env
        - apt-get install -y dos2unix
        - version=$(./update-arch-image)
        - docker tag justin8/archlinux:$version archlinux_temp
        - docker images
    ci:
        - docker run justin8/archlinux bash -c "echo test"
    post_ci:
        - docker tag archlinux_temp justin8/archlinux:latest
    push:
        - version=$(docker run --rm archlinux_temp cat /version | dos2unix)
        - echo "Pushing justin8/archlinux:$version"
        - docker push justin8/archlinux:$version
        - docker push justin8/archlinux:latest

integrations:
    hub:
        - integrationName: dockerhub
          type: docker
